package sealer

import (
	"fmt"

	commcid "github.com/filecoin-project/go-fil-commcid"
	sha256simd "github.com/minio/sha256-simd"

	"github.com/ipfs/go-cid"

	"github.com/filecoin-project/go-state-types/abi"

	"github.com/filecoin-project/lotus/storage/sealer/fr32"
	"github.com/wealdtech/go-merkletree/v2"
)

const NodeSize = 64

func GetSubpiecesWithProof(data []byte, startNode, endNode uint64) ([][]byte, *merkletree.MultiProof, error) {
	// Check if the data is empty
	if len(data) == 0 {
		return nil, nil, fmt.Errorf("data is empty")
	}

	// Check if the start and end nodes are within bounds
	if startNode > endNode || endNode >= uint64(len(data)/NodeSize) {
		return nil, nil, fmt.Errorf("invalid node range: %d-%d", startNode, endNode)
	}

	unpaddedLength := abi.UnpaddedPieceSize(len(data))
	if err := unpaddedLength.Validate(); err != nil {
		return nil, nil, fmt.Errorf("invalid unpadded length: %w", err)
	}

	// Pad the data
	paddedData := make([]byte, unpaddedLength.Padded())
	fr32.Pad(data, paddedData)

	// Chunk the padded data into nodes of size NodeSize
	retData := make([][]byte, 0, endNode-startNode+1)
	chunkedPaddedData := make([][]byte, len(paddedData)/NodeSize)
	var i uint64
	for i = 0; i < uint64(len(chunkedPaddedData)); i++ {
		chunkedPaddedData[i] = paddedData[i*NodeSize : (i+1)*NodeSize]
		if i >= startNode && i <= endNode {
			retData = append(retData, chunkedPaddedData[i])
		}
	}

	tree, err := merkletree.NewTree(merkletree.WithData(chunkedPaddedData), merkletree.WithHashType(New256()))
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create merkle tree: %w", err)
	}

	indices := make([]uint64, endNode-startNode+1)
	for i = 0; i < uint64(len(indices)); i++ {
		indices[i] = startNode + i
	}
	mp, err := tree.GenerateMultiProofWithIndices(indices)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate multi proof: %w", err)
	}

	return retData, mp, nil
}

func VerifySubpiecesProof(pieceCid cid.Cid, subPieces [][]byte, proof *merkletree.MultiProof) error {
	root, err := commcid.CIDToPieceCommitmentV1(pieceCid)
	if err != nil {
		return fmt.Errorf("failed to convert CID to piece commitment: %w", err)
	}

	ok, err := proof.Verify(subPieces, root)
	if err != nil {
		return fmt.Errorf("failed to verify proof: %w", err)
	}

	if !ok {
		return fmt.Errorf("proof verification failed")
	}

	return nil
}

// SHA256 is the 256-bit SHA-2 hashing method.
type SHA256 struct{}

// New256 creates a new 256-bit SHA-2 hashing method.
func New256() *SHA256 {
	return &SHA256{}
}

// HashLength returns the length of hashes generated by Hash() in bytes.
func (*SHA256) HashLength() int {
	return 32
}

// HashName returns the name of this hash.
func (*SHA256) HashName() string {
	return "sha256"
}

// Hash generates a SHA hash from input byte arrays.
func (*SHA256) Hash(data ...[]byte) []byte {
	var hash [32]byte
	if len(data) == 1 {
		hash = sha256simd.Sum256(data[0])
	} else {
		concatDataLen := 0
		for _, d := range data {
			concatDataLen += len(d)
		}
		concatData := make([]byte, concatDataLen)
		curOffset := 0
		for _, d := range data {
			copy(concatData[curOffset:], d)
			curOffset += len(d)
		}
		hash = sha256simd.Sum256(concatData)
	}

	hash[31] &= 0x3F

	return hash[:]
}
